if(!GENTICS.Aloha.Repositories)GENTICS.Aloha.Repositories={};GENTICS.Aloha.Repositories.Uploader=new GENTICS.Aloha.Repository("com.gentics.aloha.plugins.DragAndDropFiles");
GENTICS.Aloha.Repositories.Uploader.init=function(){this.repositoryName="Uploader";this.uploadFolder=new this.UploadFolder({id:"Uploads",name:"Uploads",displayName:"Uploads",parentId:"/",path:"Uploads",objectType:"folder",type:"folder",repositoryId:"com.gentics.aloha.plugins.DragAndDropFiles"});this.browser=new GENTICS.Aloha.ui.Browser;this.objects=[this.uploadFolder]};
GENTICS.Aloha.Repositories.Uploader.upload_conf={method:"POST",url:"",file_name_param:"filename",file_name_header:"X-File-Name",extra_headers:{},extra_post_data:{},send_multipart_form:false,www_encoded:false};
GENTICS.Aloha.Repositories.Uploader.query=function(a,b){GENTICS.Aloha.Log.info(this,"Query Uploader");console.log(a);var c=[];c=a.inFolderId=="com.gentics.aloha.plugins.DragAndDropFiles"&&a.queryString==null?this.objects:this.objects.filter(function(e){var g=RegExp(a.queryString,"i"),f=false;try{if((!a.queryString||e.url.match(g))&&a.inFolderId==e.parentId)f=true}catch(h){}return f});console.log(c);b.call(this,c)};
GENTICS.Aloha.Repositories.Uploader.getChildren=function(a,b){console.log(a);d=[];var c=a.inFolderId.split("com.gentics.aloha.plugins.DragAndDropFiles")[0];if(c=="")c="/";d=this.objects.filter(function(e){if(e.parentId==c)return true;return false});b.call(this,d)};
GENTICS.Aloha.Repositories.Uploader.addFileUpload=function(a){this.browser.show();d=this.objects.filter(function(c){if(c.name==a.name)return true;return false});if(d.length>0)return d[0];len=this.objects.length;id="GENTICS_idx_file"+len;this.objects.push(new this.File({file:a,id:id,name:a.name,displayName:a.name,parentId:"Uploads",path:"Uploads",url:"Uploads",objectType:"file",type:"file",ulProgress:0,parent:this.uploadFolder,repositoryId:"com.gentics.aloha.plugins.DragAndDropFiles"}));repoNode=this.browser.tree.getNodeById("com.gentics.aloha.plugins.DragAndDropFiles");
repoNode.expand();try{this.browser.tree.getNodeById("Uploads").select()}catch(b){}return this.objects[len]};GENTICS.Aloha.Repositories.Uploader.startFileUpload=function(a,b){d=this.objects.filter(function(c){if(c.id==a)return true;return false});d.length>0?d[0].uploadFile(Ext.apply(this.upload_conf,b)):GENTICS.Aloha.Log.error(this,"No file with that id")};GENTICS.Aloha.Repositories.Uploader.File=function(a){GENTICS.Aloha.Repositories.Uploader.File.superclass.constructor.call(this,a)};
Ext.extend(GENTICS.Aloha.Repositories.Uploader.File,GENTICS.Aloha.Repository.Document,{render:function(){try{this.parent.viewGrid.store.reload()}catch(a){}},fileAlert:function(a){if(this.fileAlertMsg===undefined||!this.fileAlertMsg.isVisible()){this.fileAlertMsgText="Error uploading:<BR>"+a;this.fileAlertMsg=Ext.MessageBox.show({title:"Upload Error",msg:this.fileAlertMsgText,buttons:Ext.Msg.OK,modal:false,icon:Ext.MessageBox.ERROR})}else{this.fileAlertMsgText+=a;this.fileAlertMsg.updateText(this.fileAlertMsgText);
this.fileAlertMsg.getDialog().focus()}},uploadFile:function(a){var b=this;extra_headers=Ext.apply(a.extra_headers,{"Content-Type":this.file.type});upload=new Ext.ux.XHRUpload({method:a.method,url:a.url,filePostName:a.file_name_param,fileNameHeader:a.file_name_header,extraHeaders:extra_headers,extraPostData:a.extra_post_data,sendMultiPartFormData:a.www_encoded,file:this.file,listeners:{scope:this,uploadloadstart:function(){b.ulStatus="Sending";b.render()},uploadprogress:function(c){b.ulProgress=Math.round(c.loaded/
c.total*100);b.render()},loadstart:function(){b.ulStatus="Sending";b.render()},progress:function(c){b.ulProgress=Math.round(c.loaded/c.total*100);b.render()},abort:function(){GENTICS.Aloha.EventRegistry.trigger(new GENTICS.Aloha.Event("UploadFailure",GENTICS.Aloha,this))},error:function(){b.ulStatus="Error";b.render();GENTICS.Aloha.EventRegistry.trigger(new GENTICS.Aloha.Event("UploadFailure",GENTICS.Aloha,this))},load:function(){try{var c=Ext.util.JSON.decode(upload.xhr.responseText)}catch(e){Ext.MessageBox.show({buttons:Ext.MessageBox.OK,
icon:Ext.MessageBox.ERROR,modal:false,title:"Upload Error!",msg:"Invalid JSON Data Returned!<BR><BR>Please refresh the page to try again."});b.ulStatus="Error";b.render();GENTICS.Aloha.EventRegistry.trigger(new GENTICS.Aloha.Event("UploadFailure",GENTICS.Aloha,this));return true}if(c.success){b.ulProgress=100;b.ulStatus="Done";b.render();b.src=c.data;GENTICS.Aloha.EventRegistry.trigger(new GENTICS.Aloha.Event("UploadSuccess",GENTICS.Aloha,this))}else{this.fileAlert("<BR>"+b.file.name+"<BR><b>"+c.error+
"</b><BR>");b.ulStatus="Error";b.render();GENTICS.Aloha.EventRegistry.trigger(new GENTICS.Aloha.Event("UploadFailure",GENTICS.Aloha,this))}}}});upload.send()}});
GENTICS.Aloha.Repositories.Uploader.UploadFolder=function(a){GENTICS.Aloha.Repositories.Uploader.UploadFolder.superclass.constructor.call(this,a);this.colModel=new Ext.grid.ColumnModel([{header:"File Name",dataIndex:"name",width:150},{header:"Size",width:80,renderer:this.fileSizeRenderer,getDataObject:this.getDataObject,columnTemplate:new Ext.XTemplate('<div class="x-grid3-cell-inner x-grid3-col-1" unselectable="on">{value}</div>')},{header:"&nbsp;",dataIndex:"attributes",width:40,renderer:this.statusIconRenderer,
getDataObject:this.getDataObject,columnTemplate:new Ext.XTemplate('<div class="x-grid3-cell-inner x-grid3-col-2" unselectable="on">{value}</div>')},{header:"Status",dataIndex:"attributes",width:80,renderer:this.statusRenderer,getDataObject:this.getDataObject,columnTemplate:new Ext.XTemplate('<div class="x-grid3-cell-inner x-grid3-col-3" unselectable="on">{value}</div>')},{header:"Progress",renderer:this.fileProgressRenderer,getDataObject:this.getDataObject,columnTemplate:new Ext.XTemplate('<div class="GENTICS_uploader-progress-cell-inner GENTICS_uploader-progress-cell-inner-center GENTICS_uploader-progress-cell-foreground">',
"<div>{value} %</div>","</div>",'<div class="GENTICS_uploader-progress-cell-inner GENTICS_uploader-progress-cell-inner-center GENTICS_uploader-progress-cell-background" style="left:{value}%">','<div style="left:-{value}%">{value} %</div>',"</div>")}])};
Ext.extend(GENTICS.Aloha.Repositories.Uploader.UploadFolder,GENTICS.Aloha.Repository.Folder,{getDataObject:function(a){repo=GENTICS.Aloha.RepositoryManager.getRepository(a.data.repositoryId);d=repo.objects.filter(function(b){if(b.id==a.data.id&&b.file)return true;return false});if(d.length>0)return d[0];return null},statusRenderer:function(a,b,c){data=this.getDataObject(c);if(data!=null){if(!data.ulStatus)data.ulStatus="Pending";return this.columnTemplate.apply({value:data.ulStatus})}},statusIconRenderer:function(a,
b,c){data=this.getDataObject(c);iconsbase=GENTICS_Aloha_base+"/plugins/com.gentics.aloha.plugins.DragAndDropFiles/resources/images/";if(data!=null){if(!data.ulStatus)data.ulStatus="Pending";switch(data.ulStatus){default:return a;case "Pending":return'<div class="GENTICS_uploader_status_icon"><img src="'+iconsbase+'hourglass.png" width=16 height=16></div>';case "Sending":return'<div class="GENTICS_uploader_status_icon"><img src="'+iconsbase+'loading.gif" width=16 height=16></div>';case "Aborted":return'<div class="GENTICS_uploader_status_icon"><img src="'+
iconsbase+'cross.png" width=16 height=16></div>';case "Error":return'<div class="GENTICS_uploader_status_icon"><img src="'+iconsbase+'cross.png" width=16 height=16></div>';case "Done":return'<div class="GENTICS_uploader_status_icon"><img src="'+iconsbase+'tick.png" width=16 height=16></div>'}}},fileSizeRenderer:function(a,b,c){data=this.getDataObject(c);if(data!=null)return this.columnTemplate.apply({value:Ext.util.Format.fileSize(data.file.size)})},fileProgressRenderer:function(a,b,c){data=this.getDataObject(c);
if(data!=null){b.css+=" x-grid3-td-progress-cell";return this.columnTemplate.apply({value:data.ulProgress})}}});
