GENTICS.Aloha.CropNResize=new GENTICS.Aloha.Plugin("com.gentics.aloha.plugins.CropNResize");GENTICS.Aloha.CropNResize.languages=["en","de"];GENTICS.Aloha.CropNResize.obj=null;GENTICS.Aloha.CropNResize.jcAPI=null;GENTICS.Aloha.CropNResize.restoreProps=[];GENTICS.Aloha.CropNResize.onResized=function(){};GENTICS.Aloha.CropNResize.onCropped=function(){};GENTICS.Aloha.CropNResize.onReset=function(){return false};GENTICS.Aloha.CropNResize.cropButton=null;GENTICS.Aloha.CropNResize.interval=null;
GENTICS.Aloha.CropNResize.attachedObjects=[];
GENTICS.Aloha.CropNResize.init=function(){var a=this;jQuery("head").append('<script type="text/javascript" src="'+GENTICS_Aloha_base+'plugins/com.gentics.aloha.plugins.CropNResize/js/jquery-ui-1.8.7.custom.min.js"><\/script><link rel="stylesheet" href="'+GENTICS_Aloha_base+'plugins/com.gentics.aloha.plugins.CropNResize/css/ui-lightness/jquery-ui-1.8.7.custom.css" /><script type="text/javascript" src="'+GENTICS_Aloha_base+'plugins/com.gentics.aloha.plugins.CropNResize/js/jquery.Jcrop.min.js"><\/script><link rel="stylesheet" href="'+GENTICS_Aloha_base+
'plugins/com.gentics.aloha.plugins.CropNResize/css/jquery.Jcrop.css" /><link rel="stylesheet" href="'+GENTICS_Aloha_base+'plugins/com.gentics.aloha.plugins.CropNResize/css/cropnresize.css" />');GENTICS.Aloha.FloatingMenu.createScope("GENTICS.Aloha.image",["GENTICS.Aloha.global"]);if(typeof this.settings.onResized=="function")this.onResized=this.settings.onResized;if(typeof this.settings.onCropped=="function")this.onCropped=this.settings.onCropped;if(typeof this.settings.onReset=="function")this.onReset=
this.settings.onReset;if(typeof this.settings.aspectRatio!="boolean")this.settings.aspectRatio=true;this.cropButton=new GENTICS.Aloha.ui.Button({size:"small",tooltip:this.i18n("Crop"),toggle:true,iconClass:"cnr_crop",onclick:function(b){b.pressed?a.crop():a.endCrop()}});GENTICS.Aloha.FloatingMenu.addButton("GENTICS.Aloha.image",this.cropButton,GENTICS.Aloha.i18n(GENTICS.Aloha,"floatingmenu.tab.image"),20);GENTICS.Aloha.FloatingMenu.addButton("GENTICS.Aloha.image",new GENTICS.Aloha.ui.Button({size:"small",
tooltip:this.i18n("Reset"),toggle:false,iconClass:"cnr_reset",onclick:function(){a.reset()}}),GENTICS.Aloha.i18n(GENTICS.Aloha,"floatingmenu.tab.image"),30);GENTICS.Aloha.EventRegistry.subscribe(GENTICS.Aloha,"selectionChanged",function(b,e,c){jQuery(c.target).hasClass("ui-resizable-handle")||a.endResize()});GENTICS.Aloha.EventRegistry.subscribe(GENTICS.Aloha,"editableCreated",function(){a.attach()})};
GENTICS.Aloha.CropNResize.attach=function(a){if(typeof a!="string")a=typeof this.settings.selector=="string"?this.settings.selector:".GENTICS_editable img";var b=this;jQuery(a).each(function(){if(!b.isAttached(this)){var e=jQuery(this);if(e.parent().hasClass("GENTICS_editicon"))return true;e.mouseup(function(c){b.focus(c);c.stopPropagation()})}})};GENTICS.Aloha.CropNResize.isAttached=function(a){for(var b=0;b<this.attachedObjects.length;b++)if(this.attachedObjects[b]===a)return true;return false};
GENTICS.Aloha.CropNResize.reset=function(){};GENTICS.Aloha.CropNResize.reset=function(){this.endCrop();this.endResize();if(!this.onReset(this.obj))for(var a=0;a<this.restoreProps.length;a++)if(this.obj.get(0)===this.restoreProps[a].obj){this.obj.attr("src",this.restoreProps[a].src);this.obj.width(this.restoreProps[a].width);this.obj.height(this.restoreProps[a].height);return}};
GENTICS.Aloha.CropNResize.initCropButtons=function(){jQuery("body").append('<div id="GENTICS_CropNResize_btns"><button class="cnr_crop_apply" title="'+this.i18n("Accept")+'" onclick="GENTICS.Aloha.CropNResize.acceptCrop();">&#10004;</button><button class="cnr_crop_cancel" title="'+this.i18n("Cancel")+'" onclick="GENTICS.Aloha.CropNResize.endCrop();">&#10006;</button></div>');var a=jQuery("#GENTICS_CropNResize_btns"),b=0,e=0;this.interval=setInterval(function(){var c=jQuery(".jcrop-tracker:first"),
d=c.offset();c.css("height")!="0px"&&c.css("width")!="0px"&&a.fadeIn("slow");d.top=parseInt(d.top+c.height()+3);d.left=parseInt(d.left+c.width()-55);if(b!=d.left||e!=d.top)a.offset(d);b=d.left;e=d.top},10)};GENTICS.Aloha.CropNResize.destroyCropButtons=function(){jQuery("#GENTICS_CropNResize_btns").remove();clearInterval(this.interval)};
GENTICS.Aloha.CropNResize.crop=function(){this.endResize();this.initCropButtons();this.jcAPI=jQuery.Jcrop(this.obj,{onSelect:function(){setTimeout(function(){GENTICS.Aloha.FloatingMenu.setScope("GENTICS.Aloha.image")},10)}})};GENTICS.Aloha.CropNResize.endCrop=function(){if(this.jcAPI){this.jcAPI.destroy();this.jcAPI=null}this.destroyCropButtons();this.cropButton.extButton.toggle(false);this.resize()};
GENTICS.Aloha.CropNResize.acceptCrop=function(){this.onCropped(this.obj,this.jcAPI.tellSelect());this.endCrop();this.resize()};GENTICS.Aloha.CropNResize.resize=function(){var a=this;this.obj.resizable({stop:function(b){a.onResized(a.obj);setTimeout(function(){GENTICS.Aloha.FloatingMenu.setScope("GENTICS.Aloha.image");a.done(b)},10)},aspectRatio:a.settings.aspectRatio,maxHeight:a.settings.maxHeight,minHeight:a.settings.minHeight,maxWidth:a.settings.maxWidth,minWidth:a.settings.minWidth,grid:a.settings.grid})};
GENTICS.Aloha.CropNResize.endResize=function(){this.obj.resizable("destroy")};GENTICS.Aloha.CropNResize.focus=function(a){GENTICS.Aloha.FloatingMenu.setScope("GENTICS.Aloha.image");this.obj=jQuery(a.target);this.restoreProps.push({obj:a.srcElement,src:this.obj.attr("src"),width:this.obj.width(),height:this.obj.height()});this.resize();this.updateFM()};GENTICS.Aloha.CropNResize.done=function(){this.updateFM()};
GENTICS.Aloha.CropNResize.updateFM=function(){var a=this.obj.offset();GENTICS.Aloha.FloatingMenu.floatTo({x:a.left,y:a.top-100})};
