<?php
// $Id: active_tags.install,v 1.1.2.2.4.2 2011/01/13 21:07:48 dragonwize Exp $

/**
 * @file
 *  Install & uninstall functions.
 */

/**
 * Implementation of hook_uninstall().
 */
function active_tags_uninstall() {
  // Delete settings from varible table.
  $sql = "DELETE FROM {variable}
          WHERE name LIKE 'active_tags%'";
  db_query($sql);
}

/**
 * Update from 6.x to 7.x.
 */
/*
function active_tags_update_7000() {

}
*/
